# Generated by Django 4.1 on 2022-09-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_moviewatchlist_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieWatchList',
            new_name='MyWatchList',
        ),
    ]
